name: Integration testing for flask app

on:
  push:
    branches:
      - main
jobs:
  test-on-main-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: Testing

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          export PYTHONPATH=$GITHUB_WORKSPACE
          python -m unittest test-integration.py
